version: '3.9'

services:
  server:
    build: .
    ports:
      - '8000:8080'
  db:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: twodo-db
    ports:
      - '4321:5432'